version: '3.3'

services:
  bot:
    build: .
    env_file:
      - ./.env
    stop_signal: SIGINT
    container_name: bot
    command: bash -c "sleep 15s;
      ./start.sh;"
    volumes:
      - ./dump/app:/usr/src/app
    networks:
      - backend


networks:
  backend:
    driver: bridge